"""Database entrypoints for the Postgres connection and schema contracts."""

from __future__ import annotations

from collections.abc import Callable
import os
from typing import Any
from urllib.parse import urlparse


ConnectFn = Callable[..., Any]
_VALID_DATABASE_SCHEMES = {"postgres", "postgresql"}


def create_connection(
    database_url: str | None = None,
    connect_fn: ConnectFn | None = None,
) -> object:
    """Create a Postgres connection using the locked v0 contract defaults."""

    resolved_database_url = _resolve_database_url(database_url)
    if connect_fn is None:
        connect_fn = _default_connect
    return connect_fn(resolved_database_url)


def initialize_schema(connection: object) -> None:
    """Initialize the project schema for the active database backend.

    Reruns intentionally hard-fail if existing data violates strengthened
    Postgres contract constraints.
    """

    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS students (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_key TEXT NOT NULL UNIQUE,
            CONSTRAINT students_student_key_nonblank
                CHECK (student_key !~ '^[[:space:]]*$')
        );

        CREATE TABLE IF NOT EXISTS template_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL,
            version INTEGER NOT NULL,
            source_yaml TEXT NOT NULL,
            CONSTRAINT template_versions_slug_version_unique UNIQUE (slug, version),
            CONSTRAINT template_versions_slug_nonblank
                CHECK (slug !~ '^[[:space:]]*$'),
            CONSTRAINT template_versions_version_positive
                CHECK (version > 0),
            CONSTRAINT template_versions_source_yaml_nonblank
                CHECK (source_yaml !~ '^[[:space:]]*$')
        );

        CREATE TABLE IF NOT EXISTS exam_definitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL,
            version INTEGER NOT NULL,
            title TEXT NOT NULL,
            template_version_id BIGINT NOT NULL REFERENCES template_versions (id),
            CONSTRAINT exam_definitions_slug_version_unique UNIQUE (slug, version),
            CONSTRAINT exam_definitions_slug_nonblank
                CHECK (slug !~ '^[[:space:]]*$'),
            CONSTRAINT exam_definitions_version_positive
                CHECK (version > 0),
            CONSTRAINT exam_definitions_title_nonblank
                CHECK (title !~ '^[[:space:]]*$')
        );

        CREATE TABLE IF NOT EXISTS exam_instances (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_definition_id BIGINT NOT NULL REFERENCES exam_definitions (id),
            student_id BIGINT NOT NULL REFERENCES students (id),
            attempt_number INTEGER NOT NULL,
            opaque_instance_code TEXT NOT NULL UNIQUE,
            CONSTRAINT exam_instances_unique_attempt_per_student_exam
                UNIQUE (exam_definition_id, student_id, attempt_number),
            CONSTRAINT exam_instances_attempt_number_positive
                CHECK (attempt_number > 0),
            CONSTRAINT exam_instances_opaque_code_nonblank
                CHECK (opaque_instance_code !~ '^[[:space:]]*$')
        );

        CREATE TABLE IF NOT EXISTS exam_pages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_instance_id BIGINT NOT NULL REFERENCES exam_instances (id),
            page_number INTEGER NOT NULL,
            fallback_page_code TEXT NOT NULL UNIQUE,
            CONSTRAINT exam_pages_unique_page_number_per_exam
                UNIQUE (exam_instance_id, page_number),
            CONSTRAINT exam_pages_page_number_positive
                CHECK (page_number > 0),
            CONSTRAINT exam_pages_fallback_page_code_nonblank
                CHECK (fallback_page_code !~ '^[[:space:]]*$')
        );

        CREATE TABLE IF NOT EXISTS scan_artifacts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sha256 TEXT NOT NULL UNIQUE,
            original_filename TEXT NOT NULL,
            status TEXT NOT NULL,
            failure_reason TEXT,
            CONSTRAINT scan_artifacts_sha256_format
                CHECK (sha256 ~ '^[0-9a-f]{64}$'),
            CONSTRAINT scan_artifacts_original_filename_nonblank
                CHECK (original_filename !~ '^[[:space:]]*$'),
            CONSTRAINT scan_artifacts_status_supported
                CHECK (status IN ('matched', 'unmatched', 'ambiguous')),
            CONSTRAINT scan_artifacts_failure_reason_rules
                CHECK (
                    (status = 'matched' AND failure_reason IS NULL)
                    OR (
                        status IN ('unmatched', 'ambiguous')
                        AND failure_reason IS NOT NULL
                        AND failure_reason !~ '^[[:space:]]*$'
                    )
                )
        );

        CREATE TABLE IF NOT EXISTS grade_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_instance_id BIGINT NOT NULL REFERENCES exam_instances (id),
            status TEXT NOT NULL,
            score_points DOUBLE PRECISION NOT NULL,
            max_points DOUBLE PRECISION NOT NULL,
            CONSTRAINT grade_records_status_supported
                CHECK (status IN ('draft', 'finalized')),
            CONSTRAINT grade_records_score_points_nonnegative
                CHECK (score_points >= 0),
            CONSTRAINT grade_records_max_points_positive
                CHECK (max_points > 0),
            CONSTRAINT grade_records_score_points_within_max
                CHECK (score_points <= max_points)
        );

        CREATE TABLE IF NOT EXISTS audit_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            entity_id BIGINT NOT NULL,
            event_type TEXT NOT NULL,
            payload_json JSONB NOT NULL,
            recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT audit_events_entity_type_nonblank
                CHECK (entity_type !~ '^[[:space:]]*$'),
            CONSTRAINT audit_events_event_type_nonblank
                CHECK (event_type !~ '^[[:space:]]*$')
        );

        -- Intentionally hard-fail reruns until legacy rows that violate the
        -- strengthened all-whitespace contract are cleaned up.
        ALTER TABLE students
        DROP CONSTRAINT IF EXISTS students_student_key_nonblank;
        ALTER TABLE students
        ADD CONSTRAINT students_student_key_nonblank
            CHECK (student_key !~ '^[[:space:]]*$');

        ALTER TABLE template_versions
        DROP CONSTRAINT IF EXISTS template_versions_slug_nonblank;
        ALTER TABLE template_versions
        ADD CONSTRAINT template_versions_slug_nonblank
            CHECK (slug !~ '^[[:space:]]*$');
        ALTER TABLE template_versions
        DROP CONSTRAINT IF EXISTS template_versions_source_yaml_nonblank;
        ALTER TABLE template_versions
        ADD CONSTRAINT template_versions_source_yaml_nonblank
            CHECK (source_yaml !~ '^[[:space:]]*$');

        ALTER TABLE exam_definitions
        DROP CONSTRAINT IF EXISTS exam_definitions_slug_nonblank;
        ALTER TABLE exam_definitions
        ADD CONSTRAINT exam_definitions_slug_nonblank
            CHECK (slug !~ '^[[:space:]]*$');
        ALTER TABLE exam_definitions
        DROP CONSTRAINT IF EXISTS exam_definitions_title_nonblank;
        ALTER TABLE exam_definitions
        ADD CONSTRAINT exam_definitions_title_nonblank
            CHECK (title !~ '^[[:space:]]*$');

        ALTER TABLE exam_instances
        DROP CONSTRAINT IF EXISTS exam_instances_opaque_code_nonblank;
        ALTER TABLE exam_instances
        ADD CONSTRAINT exam_instances_opaque_code_nonblank
            CHECK (opaque_instance_code !~ '^[[:space:]]*$');

        ALTER TABLE exam_pages
        DROP CONSTRAINT IF EXISTS exam_pages_fallback_page_code_nonblank;
        ALTER TABLE exam_pages
        ADD CONSTRAINT exam_pages_fallback_page_code_nonblank
            CHECK (fallback_page_code !~ '^[[:space:]]*$');

        ALTER TABLE scan_artifacts
        DROP CONSTRAINT IF EXISTS scan_artifacts_original_filename_nonblank;
        ALTER TABLE scan_artifacts
        ADD CONSTRAINT scan_artifacts_original_filename_nonblank
            CHECK (original_filename !~ '^[[:space:]]*$');
        ALTER TABLE scan_artifacts
        DROP CONSTRAINT IF EXISTS scan_artifacts_failure_reason_rules;
        ALTER TABLE scan_artifacts
        ADD CONSTRAINT scan_artifacts_failure_reason_rules
            CHECK (
                (status = 'matched' AND failure_reason IS NULL)
                OR (
                    status IN ('unmatched', 'ambiguous')
                    AND failure_reason IS NOT NULL
                    AND failure_reason !~ '^[[:space:]]*$'
                )
            );

        ALTER TABLE audit_events
        DROP CONSTRAINT IF EXISTS audit_events_entity_type_nonblank;
        ALTER TABLE audit_events
        ADD CONSTRAINT audit_events_entity_type_nonblank
            CHECK (entity_type !~ '^[[:space:]]*$');
        ALTER TABLE audit_events
        DROP CONSTRAINT IF EXISTS audit_events_event_type_nonblank;
        ALTER TABLE audit_events
        ADD CONSTRAINT audit_events_event_type_nonblank
            CHECK (event_type !~ '^[[:space:]]*$');

        CREATE UNIQUE INDEX IF NOT EXISTS grade_records_one_finalized_per_exam_instance
            ON grade_records (exam_instance_id)
            WHERE status = 'finalized';

        CREATE OR REPLACE FUNCTION prevent_versioned_row_updates()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'versioned table rows are immutable';
        END;
        $$;

        DROP TRIGGER IF EXISTS template_versions_immutable ON template_versions;
        CREATE TRIGGER template_versions_immutable
        BEFORE UPDATE ON template_versions
        FOR EACH ROW
        EXECUTE FUNCTION prevent_versioned_row_updates();

        DROP TRIGGER IF EXISTS exam_definitions_immutable ON exam_definitions;
        CREATE TRIGGER exam_definitions_immutable
        BEFORE UPDATE ON exam_definitions
        FOR EACH ROW
        EXECUTE FUNCTION prevent_versioned_row_updates();
        """
    )


def _resolve_database_url(database_url: str | None) -> str:
    if database_url is None:
        database_url = os.environ.get("DATABASE_URL")
        if database_url is None:
            raise ValueError(
                "database_url is required; pass database_url or set DATABASE_URL."
            )

    return _normalize_postgres_database_url(database_url, label="database_url")


def _normalize_postgres_database_url(database_url: str, *, label: str) -> str:
    stripped_database_url = database_url.strip()
    if stripped_database_url == "":
        raise ValueError(f"{label} must not be blank or whitespace.")
    if stripped_database_url != database_url:
        raise ValueError(
            f"{label} must not include leading or trailing whitespace."
        )

    parsed_database_url = urlparse(database_url)
    if parsed_database_url.scheme.lower() not in _VALID_DATABASE_SCHEMES:
        raise ValueError(
            f"{label} must use a Postgres URL scheme: postgres:// or postgresql://."
        )

    return (
        f"{parsed_database_url.scheme.lower()}"
        f"{database_url[len(parsed_database_url.scheme):]}"
    )


def _default_connect(database_url: str) -> object:
    import psycopg
    from psycopg.rows import dict_row

    return psycopg.connect(
        database_url,
        autocommit=True,
        row_factory=dict_row,
    )
